# Generated by Django 2.1.7 on 2019-06-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio_venta', models.FloatField(max_length=50)),
                ('productosxMenu', models.ManyToManyField(to='stock.Producto')),
            ],
        ),
    ]
