# Generated by Django 2.1.7 on 2019-06-06 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuxProductos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='menu',
            name='productosxMenu',
        ),
        migrations.AddField(
            model_name='menuxproductos',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Menu'),
        ),
        migrations.AddField(
            model_name='menuxproductos',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Producto'),
        ),
        migrations.AddField(
            model_name='menu',
            name='menuxProductos',
            field=models.ManyToManyField(through='menu.MenuxProductos', to='stock.Producto'),
        ),
    ]
