# Generated by Django 2.2 on 2019-05-29 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='telefono2',
        ),
    ]
